language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
env:
  - PYTHONPATH=$(pwd)
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - make clean
  - make convert
  - make all
